[package]
name = "passwg"
version = "1.7.1"
edition = "2024"

[dependencies]
arboard = "3.6.1"
getrandom = "0.3.4"
itoa = "1.0.17"
rand_chacha = "0.9.0"
rand_core = "0.9.5"
rayon = "1.11.0"

[profile.release]
opt-level = "z"
lto = true 
codegen-units = 1
panic = "abort"
strip = true
