[package]
name = "passwg"
version = "0.5.2"
edition = "2024"

[dependencies]
arboard = "3.6.1"
getrandom = "0.3.4"
rayon = "1.11.0"

[profile.release]
opt-level = "z"
lto = true 
codegen-units = 1
panic = "abort"
strip = true
